version = 3

[[blocks]]
  type = 'newline'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{ .UserName }} on '
    foreground = '#45F1C2'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = '#0CA0D8'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_separator_icon = '/'
      style = 'agnoster_short'
      max_depth = 2

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}'
    foreground = '#14A5AE'
    powerline_symbol = ''
    type = 'git'
    style = 'plain'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}{{ end }}', '{{ if gt .Ahead 0 }}{{ end }}', '{{ if gt .Behind 0 }}{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true

      [blocks.segments.properties.untracked_modes]
        '/Users/user/Projects/oh-my-posh/' = 'no'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }} {{ else }}{{ if .Version }} {{.Version }}{{ end }} {{ if .Name }}{{ .Name }}{{ end }} {{ end }}  '
    foreground = '#14A5Ae'
    type = 'project'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    powerline_symbol = ''
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
      style = 'austin'
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ''
    foreground = '#cd5e42'
    type = 'root'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '# '
    foreground = '#CD4277'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
