function systemKey(key)
	hs.eventtap.event.newSystemKeyEvent(key, true):post()
	hs.eventtap.event.newSystemKeyEvent(key, false):post()
end

-- important applications
hs.hotkey.bind({}, "F1", function()
	hs.application.launchOrFocus("Brave Browser")
end)

hs.hotkey.bind({}, "F2", function()
	hs.application.launchOrFocus("Ghostty")
end)

-- hs.hotkey.bind({}, "F3", function()
--	hs.application.launchOrFocus("RustRover")
-- end)
-- hs.hotkey.bind({}, "F4", function()
-- 	hs.application.launchOrFocus("WebStorm")
-- end)
hs.hotkey.bind({}, "F5", function()
	hs.application.launchOrFocus("ZenNotes")
end)

-- simulate media keys
hs.hotkey.bind({}, "F7", function()
	systemKey("PREVIOUS")
end)
hs.hotkey.bind({}, "F8", function()
	systemKey("PLAY")
end)
hs.hotkey.bind({}, "F9", function()
	systemKey("NEXT")
end)
hs.hotkey.bind({}, "F10", function()
	systemKey("MUTE")
end)
hs.hotkey.bind({ "cmd" }, "F11", function()
	systemKey("SOUND_DOWN")
end)
hs.hotkey.bind({}, "F12", function()
	systemKey("SOUND_UP")
end)
